config/routes.rb
Doubtsync::Application.routes.draw do
  

  get 'search' => 'search#query'
  get "resume/daiict"
  get "ambassador/proflist"
  post "ambassador/proflist" => 'ambassador#uploadFile'
  get "ambassador/resumeformat"
  get "colleges/new"
  post "colleges/new" => 'colleges#create'
  get "colleges/:id" => 'colleges#show'
  post "colleges/ambassadorregistration" => 'colleges#update'
  
  devise_for :users, path: "", path_names: { sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: '' }, :controllers => { :registrations => 'registers' }

  get "users/manage" => 'users#manage'
  post "users/manage" => 'users#save'
  get "users/profile" => 'users#profile'
  get "users/:id" => 'users#index'
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  get "main/index"
  get "main/feed"
  get 'main/user' => 'main#user'
  get 'main/topic' => 'main#topic'
  get 'main/notificationlist' => 'main#notificationlist'
  get 'main/unreadmsg' => 'main#unreadmsg'

  post 'posts/file'
  
   
  resources :posts
  resources :relationships, only: [:create, :destroy]
  resources :followed_topics, only: [:create, :destroy]

  post 'message/:id' => 'messages#send_message'
  get 'message' => 'messages#list_message'

  post 'comments' => 'comments#create'
  get 'comments/:id' => 'comments#index'
  post 'comments/:id/edit' => 'comments#edit'
  post 'comments/:id/up' => 'comments#upvote'
  post 'comments/:id/down' => 'comments#downvote'
  post 'comments/:id/spam' =>'comments#spam'
  post 'posts/:id/spam' =>'posts#spam'
  get 'posts/:id/index' =>'posts#list'
  get 'comments/:id/index' =>'comments#list'
  delete 'comments/:id' => 'comments#destroy'

  get 'topics/:name' => 'topics#index'
  get 'exploretopic' => 'topics#explore'

  post 'books' => 'books#new'
  get 'books/:id' => 'books#show'
  post 'books/:id/edit' => 'books#edit'
  delete 'books/:id' => 'books#destroy'

  post 'internship' => 'internships#new'
  get 'internships/list' => 'internships#myinternship'
  get 'internship/:id' => 'internships#show'
  post 'internship/:id/edit' => 'internships#edit'
  delete 'internship/:id' => 'internships#destroy'
  get "internships" => 'internships#list'
  get "internships/:id/response" => 'internships#internship_response'
  post "internship/apply" => 'internships#apply'

  post 'events' => 'events#new'
  get 'events/date/:date' => 'events#search_date'
  post 'events/:id/edit' => 'events#edit'
  get 'events/:id' => 'events#show'
  delete 'events/:id' => 'events#destroy'

  root 'home#index'
  

end
  

app/controllers/home_controller.rb
class HomeController < ApplicationController
	layout 'home'
	def index
		if current_user
			redirect_to '/main/feed'
		end
	end
end

app/helpers/home_helper.rb
module HomeHelper
 def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/home/index.html.erb
<div class="navbar navbar-collapse collapse">
<div class="navbar-header">
  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
    <span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
  </button>
  <b class="navbar-brand">DoubtSync</b>
</div>

  <ul class="nav navbar-nav">
    <li>
      <a href="#about">About</a>
    </li>
    <li>
      <a href="#contact">Contact</a>
    </li>
    
  </ul>
  
  <!--/.navbar-collapse -->
</div>

<br>
<div class="container">
<% if !current_user.nil? %>
<%= current_user.username %>
  <!-- render feed page -->
  <li>
  <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
  </li>
<% else %>
<div class="row">
	<div class="col-md-9">
	
		<div class="jumbotron" style=" background:url('/images/mainbg.jpg');background-size:100%;box-shadow: 0px 0px 10px #000;">
        <!-- <button type="submit" class="btn pull-right btn-primary btn-lg">Sign up</button>
          <h4 style="color:#008000; margin-right:20px" class="pull-right">  Not a member yet? </h4> -->
        <div class="container" style="color:#ddd;text-shadow: 0px 0px 1px #eee;">
          <div class="filter"></div>
          <h1>Doubtsync</h1>
          <p>This is the ultimate platform for all your academic needs. Doubts Solving, Creating Resumes, </p>
          <p>Looking for research opportunities and interacting with professors. We are here to solve them</p>
          <p>all. </p>
          <p><a class="btn btn-primary btn-lg">Learn more</a></p>
        </div>
      </div>
	</div>
  <div class="col-md-3 pull-right">
<%= form_for(resource, :as => resource_name,:url => session_path(:user), html: {role: 'form',id:'loginform' } ) do |f| %>

  <%= alert %>
  <div class="form-group">
    <%= f.label :username %>
      <%= f.text_field :username, class: 'form-control', placeholder: "Enter username",:autofocus=>true %>
  </div>
  <div class="form-group">  
  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control', placeholder: "password" %>
  </div>
    <%= f.check_box :remember_me %>
    <%= f.label :remember_me %><br>
    <%= f.submit 'Sign in', class: 'btn btn-primary login',id:'loginbtn' %>
    <a href="register"><%= f.submit 'Sign up', class: 'btn btn-default register', type: 'button',id: 'registerbtn' %></a><br>
    <%= link_to "Forgot your password?", new_password_path(:user) %>
  <% end %>

  </div>
  </div>
		<div class="row">
          <div class="col-lg-4">
            <h2> Doubts Solving </h2>
            <p>Are you the shy one in the class room? Are doubts piling up and your only resort is the 'studious' friend. Move over it. Doubtsync is the platform where you can shed off all your shyness and interact with the best in each topic.</p>
            </div>
          <div class="col-lg-4">
            <h2>Looking for Research? </h2>
            <p>Doubtsync is the ultimate abode for all you research craving minds. Search for topics your are interested in. Search for your favorite professors- Whom you wish to work with. </p>
            <!-- <p><a class="btn btn-default" href="#">View details</a></p> -->
          </div>
          <div class="col-lg-4">
            <h2>Creating Resumes</h2>
            <p>Confused between what a resume for a job and a resume for Placements look like? Don't you worry- We are here to solve all your problems. </p>
            <!-- <p><a class="btn btn-default" href="#">View details</a></p> -->
          </div>
    </div>
	
	


<% end %>
</div>